> drone_datafile/txtfile/excel_data/Shell_Etd_average.txt
> drone_datafile/txtfile/excel_data/Shell_Eti_average.txt
> drone_datafile/txtfile/excel_data/Shell_Etg_average.txt
> drone_datafile/txtfile/excel_data/Shell_flight_time_average.txt
> drone_datafile/txtfile/excel_data/Shell_TV_chargecount.txt
> drone_datafile/txtfile/excel_data/Shell_TV_chargeAmount.txt
> drone_datafile/txtfile/excel_data/Shell_Med_re_average.txt
> drone_datafile/txtfile/excel_data/Shell_Med_re_collect_to_delivery_average.txt
> drone_datafile/txtfile/excel_data/Shell_MedInf_average.txt
> drone_datafile/txtfile/excel_data/Shell_Medinf_collect_average.txt
> drone_datafile/txtfile/excel_data/Shell_DroneDeliveryProbability_average.txt
> drone_datafile/txtfile/excel_data/Shell_Etc_dro_average.txt
> drone_datafile/txtfile/excel_data/Shell_Etc_to_Vehicle_average.txt
> drone_datafile/txtfile/excel_data/Shell_Etc_Vehicle_average.txt
> drone_datafile/txtfile/excel_data/Shell_Etc_Dro+Vehicle_average.txt
> drone_datafile/txtfile/excel_data/Shell_InfCdrone_TripTime.txt
> drone_datafile/txtfile/excel_data/Shell_Jyunkai_time_Infd_ave.txt
> drone_datafile/txtfile/excel_data/Shell_Prob_Medinf_drone.txt